### ISSUE TITLE
Dynamically education

### ISSUE THREAD

**Issue by eerison** [shield-w4ll/CurriculumBundle#25]
## Story

As a user with **any professional experience** and with few things to add in my CV, I want to see my education in the main area, to see my CV more populated

## ACs
- if the user has less then 2 experiences, you will hide the education in the left side and move to main CV area
![Screenshot 2022-06-15 at 15 09 24](https://user-images.githubusercontent.com/6358755/173835115-61eb9686-16d4-44ef-aaa3-760f0a2a94b2.png)
- Make sure that the education section has the same layout of Experiences
- Create a component for education and use the same component in both side (left side and main side) 

## QA
- Create a CV with one or any experience and see if the education section desapear in from the left side and appear in the main area
- Create a CV with more then 2 experiences and check if the education section is in the left side and not in the main area
- Make sure that will appear the **education title** only when exist some education added.

**Comment by eerison** [comment]
Hey @Willian1661 what do you think you do this feature? I guess it'll be really important for your CV

**Comment by eerison** [comment]
@Willian1661 after you finish the implementation check if it's missing some QA criterial to be added!

**Comment by Willian1661** [comment]
ok, so what have to be done is that if the user have less then 2 experiences the EDUCATION it will have to appear on the left side with the same layout as the EXPERIENCES and if it have 2 or more will maintain on the right side,right?

**Comment by eerison** [comment]
> OK, so what have to be done is: 1-when the user have less then 2 experiences **the education** it will have to appear on the left side with the same layout as in **the experiences**.
> 
> 2-if it has 2 or more experiences **the education** will maintain on the right side,right?

exactly ;)
