### ISSUE TITLE
Remove empty comma

### ISSUE THREAD

**Issue by eerison** [shield-w4ll/CurriculumBundle#31]
### Story
for address with city only like `Berlin, Germany`, it's appearing an empty comma for example:
![Screenshot 2022-06-20 at 17 07 01](https://user-images.githubusercontent.com/6358755/174631544-72d17e3d-09b7-4000-8e8e-32821c20e5fb.png), 

Then we expect something like this: `Berlin, Germany`

### Note

you can get some use cases like this:

- City, Contry
- City, State, Country
- State, Contry

**Comment by SpaceX-CK** [comment]
hope this will help, javascript 

`let item = ['Berlin', 'Germany', 'UK'];
// 
   let newitem = item.map(function(val, index){
    if (index !== 0){
        item = (','+ item);
    return  ','+ val
    }
    else{
     return val;
    }
}) 
console.log("🚀 ~ item", newitem)
//["Berlin",",Germany",",UK"]`

**Comment by eerison** [comment]
Hi @SpaceX-CK 

thank you for the suggestion, But we are not using JS to handle this logical, we are using [twig](https://twig.symfony.com/doc/3.x/), But it's quite easy to get some examples into the doc, if you want to provide some Pull request fell free :)
